export type Game = {
  id: string;
  title: string;
  embed: string;
  url: string;
  image: string;
  thumbnail: string;
  tags: string;
  description: string;
  category: string;
  views: number;
  date: string;
  developer: string;
};

export const games: Game[] = [
  {
    "id": "love-tester",
    "title": "Love Tester",
    "embed": "https://www.onlinegames.io/games/2021/3/love-tester/index.html",
    "url": "https://www.onlinegames.io/games/2021/3/love-tester/index.html",
    "image": "https://www.onlinegames.io/media/posts/152/responsive/love-tester-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/152/responsive/love-tester-xs.jpg",
    "tags": "1-player,2d,free,fun,funny,girl,html5,kids,love,mobile",
    "description": "Do you want to know how much your crush falls for you?  Here is a way to test the love of the one and only.  Love Tester is an online game where you fill out your and your crush's names.  Then, let the tester do all the calculations about how much they love you, miss you during the day, or have any second thoughts about you.",
    "category": "Girl",
    "views": 1967825,
    "date": "2021-04-23T10:22:42",
    "developer": "Retro Works"
  },
  {
    "id": "drift-king",
    "title": "Drift King",
    "embed": "https://www.onlinegames.io/games/2024/unity/drift-king/index.html",
    "url": "https://www.onlinegames.io/games/2024/unity/drift-king/index.html",
    "image": "https://www.onlinegames.io/media/posts/729/responsive/Drift-King-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/729/responsive/Drift-King-xs.jpg",
    "tags": "3d,car,crazy,drift,driving,free,multiplayer,simulator,speed,unity",
    "description": "Drift King stands out among online drift games, offering a unique experience where you can witness the smoke you leave behind from the rearview window.  This game surrounds you in every realistic detail, from its premium 3D visuals to the choice of 10 sports cars and 6 maps. \nThe comprehensive tuning options further enhance the game, making it a complete package for drifting enthusiasts. \n\n\nControls\n\nWASD or arrow keys: Move car \nM: Rearview Mirror\nC: Change Carnera\nR: Reset Car\nU: Toggle between KMH and MPH\nI: Start/Stop Engine\nP: Fullscreen\n\n\n\nHow To Play Drift King\nThe traditional approach in a car game would be to give zero cash to the player at the beginning.",
    "category": "Drift",
    "views": 4208603,
    "date": "2022-06-03T10:22:42",
    "developer": "Arcade Masters"
  },
  {
    "id": "stack-fire-ball",
    "title": "Stack Fire Ball",
    "embed": "https://www.onlinegames.io/games/2021/unity/stack-fire-ball/index.html",
    "url": "https://www.onlinegames.io/games/2021/unity/stack-fire-ball/index.html",
    "image": "https://www.onlinegames.io/media/posts/184/responsive/Stack-Fire-Ball-Game-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/184/responsive/Stack-Fire-Ball-Game-xs.jpg",
    "tags": "1-player,3d,arcade,avoid,ball,color,crazy,destroy,free,mobile,mouse,skill",
    "description": "Reach the end by guiding the ball through each stage, avoiding the dark tiles. This game is a combination between relaxation but also keeping attention to details. With modern graphics, you will enjoy knocking down the colorful tiles as fast as you can.  Let the ball bounce and complete all the stages.",
    "category": "Arcade",
    "views": 1819583,
    "date": "2024-12-17T10:22:42",
    "developer": "Pixel Dreams"
  },
  {
    "id": "highway-traffic",
    "title": "Highway Traffic",
    "embed": "https://www.onlinegames.io/games/2022/unity/highway-traffic/index.html",
    "url": "https://www.onlinegames.io/games/2022/unity/highway-traffic/index.html",
    "image": "https://www.onlinegames.io/media/posts/32/responsive/Highway-Traffic-2-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/32/responsive/Highway-Traffic-2-xs.jpg",
    "tags": "1-player,3d,car,crash,crazy,driving,endless,free,police,racing,speed,traffic,unity",
    "description": "Highway Traffic game is centered around driving down the highway, dodging other cars, and avoiding accidents.  It gets tricky because other vehicles are slowing down, speeding up or stopping abruptly, so you always have to keep your attention and be ready to make a quick maneuver.  \nThe longer you go without hitting other cars, the more points you collect and the more upgrades you can get.  Highway Traffic gets challenging very quickly, so you must build up crazy driving skills to reach higher levels!",
    "category": "Racing",
    "views": 1558591,
    "date": "2024-06-24T10:22:42",
    "developer": "Velocity Studios"
  },
  {
    "id": "gta-simulator",
    "title": "GTA Simulator",
    "embed": "https://www.onlinegames.io/games/2023/unity2/gta-simulator/index.html",
    "url": "https://www.onlinegames.io/games/2023/unity2/gta-simulator/index.html",
    "image": "https://www.onlinegames.io/media/posts/416/responsive/GTA-Simulator-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/416/responsive/GTA-Simulator-xs.jpg",
    "tags": "1-player,3d,action,car,driving,free,gta,shooting,simulator,traffic,unity",
    "description": "You know that famous GTA video game series, right?  Well, meet its online and free version on OnlineGames. io.  GTA Simulator is a simulator game that you can play on your web browser without the need to download.",
    "category": "Shooting",
    "views": 633224,
    "date": "2021-05-03T10:22:42",
    "developer": "GameForge"
  },
  {
    "id": "real-flight-simulator",
    "title": "Real Flight Simulator",
    "embed": "https://cloud.onlinegames.io/games/2023/unity2/real-flight-simulator/index.html",
    "url": "https://cloud.onlinegames.io/games/2023/unity2/real-flight-simulator/index.html",
    "image": "https://www.onlinegames.io/media/posts/342/responsive/Real-Flight-Simulator-2-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/342/responsive/Real-Flight-Simulator-2-xs.jpg",
    "tags": "1-player,3d,airplane,flying,free,simulator,unity",
    "description": "Real Flight Simulator is a realistic game that gives you the ultimate flight experience. There is the possibility to choose the aircraft you want and start to control the plane. You will become an expert in controlling the planes, reaching the heights and exploring skies. You will be able to test the following aircrafts:• A-10• A-29• F-35• KC-10 • M-262Follow the instructions to make the aircraft fly:1.",
    "category": "Simulator",
    "views": 3768136,
    "date": "2022-06-22T10:22:42",
    "developer": "GameVerse"
  },
  {
    "id": "backflip-challenge",
    "title": "Backflip Challenge",
    "embed": "https://cloud.onlinegames.io/games/2026/unity/backflip-challenge/game.html",
    "url": "https://cloud.onlinegames.io/games/2026/unity/backflip-challenge/game.html",
    "image": "https://www.onlinegames.io/media/posts/1203/responsive/backflip-challenge-xs.webp",
    "thumbnail": "https://www.onlinegames.io/media/posts/1203/responsive/backflip-challenge-xs.webp",
    "tags": "1-player,3d,avoid,free,funny,mobile,mouse,physics,skill,sports,unity,water",
    "description": "Backflip Challenge is an online skill game in which you help the grandpa to backflip from a high place.  Make him do a backflip with his elastic body by jumping from the trampoline.  However, you need to be extra cautious since his bones are fragile.  Avoid smashing his bones.",
    "category": "Sports",
    "views": 545199,
    "date": "2024-04-25T10:22:42",
    "developer": "Studio X"
  },
  {
    "id": "masked-special-forces",
    "title": "Masked Special Forces",
    "embed": "https://www.onlinegames.io/games/2022/unity2/masked-special-forces/index.html",
    "url": "https://www.onlinegames.io/games/2022/unity2/masked-special-forces/index.html",
    "image": "https://www.onlinegames.io/media/posts/310/responsive/Masked-Special-Forces-FPS-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/310/responsive/Masked-Special-Forces-FPS-xs.jpg",
    "tags": "3d,action,armor,battle-royale,first-person-shooter,free,gun,io-games,multiplayer,shooting,war,weapon",
    "description": "Masked Special Forces is a multiplayer first-person shooter game with a myriad of customization options.  The game puts you in the shoes of a commander in the battle arena.  As a talented warrior, team up, strategize, and take down the opponents one by one.  \nAccess to an array of upgradable weapons, armory, kill messages, and victory dances on the main menu.",
    "category": "Shooting",
    "views": 9242600,
    "date": "2023-07-10T10:22:42",
    "developer": "Digital Dreams"
  },
  {
    "id": "madalin-stunt-cars-pro",
    "title": "Madalin Stunt Cars Pro",
    "embed": "https://www.onlinegames.io/games/2023/unity/madalin-stunt-cars-pro/index.html",
    "url": "https://www.onlinegames.io/games/2023/unity/madalin-stunt-cars-pro/index.html",
    "image": "https://www.onlinegames.io/media/posts/401/responsive/Madalin-Stunt-Cars-Pro-Game-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/401/responsive/Madalin-Stunt-Cars-Pro-Game-xs.jpg",
    "tags": "3d,car,crazy,drift,driving,free,multiplayer,speed,stunt,unity",
    "description": "Are you open to experiencing luxury?  The 3D driving game Madalin Stunt Cars Pro features excellent graphics for lifelike experiences.  You can choose from various vehicles in Madalin Stunt Cars Pro, from the most opulent sports cars to a police cruiser, in three distinct map areas. \nHow to play Madalin Stunt Cars Pro?",
    "category": "Drift",
    "views": 7636477,
    "date": "2024-06-21T10:22:42",
    "developer": "Retro Works"
  },
  {
    "id": "stickman-gta-city",
    "title": "Stickman GTA City",
    "embed": "https://cloud.onlinegames.io/games/2024/unity3/stickman-gta-city/index-og.html",
    "url": "https://cloud.onlinegames.io/games/2024/unity3/stickman-gta-city/index-og.html",
    "image": "https://www.onlinegames.io/media/posts/900/responsive/stickman-gta-city-free-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/900/responsive/stickman-gta-city-free-xs.jpg",
    "tags": "1-player,3d,action,adventure,battle,car,driving,free,gta,gun,shooting,simulator,traffic,unity,weapon",
    "description": "You've been digging the internet for ages, looking for a free GTA game to play on your browser, only to end up with games that disappoint faster than a balloon losing air.  You might have given up hope, reminiscing about the days of cruising through GTA San Andreas or Vice City with your bro.  Think of how much you missed even hearing that iconic sound, the one that plays right as the screen fades to black with a bold \"Wasted! \" slapped across it?",
    "category": "Shooting",
    "views": 209031,
    "date": "2025-06-04T10:22:42",
    "developer": "DevHub"
  },
  {
    "id": "stickman-parkour",
    "title": "Stickman Parkour",
    "embed": "https://cloud.onlinegames.io/games/2024/construct/219/stickman-parkour/index-og.html",
    "url": "https://cloud.onlinegames.io/games/2024/construct/219/stickman-parkour/index-og.html",
    "image": "https://www.onlinegames.io/media/posts/871/responsive/stickman-parkour-OG-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/871/responsive/stickman-parkour-OG-xs.jpg",
    "tags": "1-player,2d,action,adventure,arcade,free,fun,mobile,parkour,physics,running,stickman",
    "description": "Stickman Parkour is an online platformer game that you can play on your browser, embracing the easy-to-learn but hard-to-master mechanics.  Collect keys, open chests, pass levels and help him find his way out across 30 levels. \nWhat is Stickman Parkour about? \nImagine Stickman, a tiny stick figure who decides one day to go on this epic adventure.",
    "category": "Action",
    "views": 7190293,
    "date": "2023-01-28T10:22:42",
    "developer": "Retro Works"
  },
  {
    "id": "get-on-top",
    "title": "Get On Top",
    "embed": "https://www.onlinegames.io/games/2024/code/6/get-on-top/index.html",
    "url": "https://www.onlinegames.io/games/2024/code/6/get-on-top/index.html",
    "image": "https://www.onlinegames.io/media/posts/697/responsive/Get-on-Top-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/697/responsive/Get-on-Top-xs.jpg",
    "tags": "2-player,2d,action,arcade,battle,combat,crazy,free,fun,html5,physics,stickman",
    "description": "Remember those days when you and your brother used to wrestle for hours until one of you cried and complained to Mom?  It was a real duel, wasn't it?  You would flip over together like a human ball, with arms and legs flying in the air.  So, we've brought sibling wrestling to the virtual realm.",
    "category": "2 Player",
    "views": 2708513,
    "date": "2022-05-17T10:22:42",
    "developer": "Nexus Labs"
  },
  {
    "id": "drift-hunters-pro",
    "title": "Drift Hunters Pro",
    "embed": "https://www.onlinegames.io/games/2023/unity/drift-hunters-pro/index.html",
    "url": "https://www.onlinegames.io/games/2023/unity/drift-hunters-pro/index.html",
    "image": "https://www.onlinegames.io/media/posts/397/responsive/Drift-Hunters-Pro-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/397/responsive/Drift-Hunters-Pro-xs.jpg",
    "tags": "3d,car,crash,drift,driving,free,multiplayer,racing,speed,stunt,unity",
    "description": "Can you hear the engine moaning?  Drift Hunters Pro is a thrilling 3D game with high-quality graphics for those who are fond of drifting &amp; racing.  You can play solely, or you can play on the servers with other players.  In this game, you have 6 different tracks and 10 upgradable vehicles in the garage that you can buy with earnings via drifting.",
    "category": "Drift",
    "views": 1814803,
    "date": "2021-09-08T10:22:42",
    "developer": "Quantum Games"
  },
  {
    "id": "dublix",
    "title": "Dublix",
    "embed": "https://cloud.onlinegames.io/games/2025/unity4/dublix/game-og.html",
    "url": "https://cloud.onlinegames.io/games/2025/unity4/dublix/game-og.html",
    "image": "https://www.onlinegames.io/media/posts/1126/responsive/dublix-xs.webp",
    "thumbnail": "https://www.onlinegames.io/media/posts/1126/responsive/dublix-xs.webp",
    "tags": "3d,adventure,crazy,free,fun,kart,multiplayer,music,parkour,racing,roblox,unity",
    "description": "Dublix is an online multiplayer game with its exciting Roblox-inspired World!  Wander in the maze to find the exit, take your part in the parkour and drive a car in the race-track to earn coins.  The best way to end the night is to dance freely at the music festival. \nControls\n\nWASD or Arrow Keys: Move\nSpacebar: Jump\nLeft-Shift: Run\nE Key: Interact\n\nHow to Play Dublix\nWell, Dublix offers its players a free Roblox-inspired world.",
    "category": "Adventure",
    "views": 1722631,
    "date": "2023-03-08T10:22:42",
    "developer": "Pixel Forge"
  },
  {
    "id": "edys-car-simulator",
    "title": "Edys Car Simulator",
    "embed": "https://www.onlinegames.io/games/2022/unity/edys-car-simulator/index.html",
    "url": "https://www.onlinegames.io/games/2022/unity/edys-car-simulator/index.html",
    "image": "https://www.onlinegames.io/media/posts/238/responsive/Edys-Car-Simulator-Online-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/238/responsive/Edys-Car-Simulator-Online-xs.jpg",
    "tags": "1-player,3d,car,crash,driving,free,racing,simulator,speed,stunt",
    "description": "Do you fancy doing some sightseeing?  Edy's Car Simulator is a game where you can freely wander the streets!  The city is all yours.  You are free to use the whole city however you want.",
    "category": "Racing",
    "views": 4537923,
    "date": "2025-09-10T10:22:42",
    "developer": "Pixel Studios"
  },
  {
    "id": "guerrillas-io",
    "title": "Guerrillas io",
    "embed": "https://www.onlinegames.io/games/2023/unity2/guerrillas-io/index.html",
    "url": "https://www.onlinegames.io/games/2023/unity2/guerrillas-io/index.html",
    "image": "https://www.onlinegames.io/media/posts/423/responsive/Guerillas-io-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/423/responsive/Guerillas-io-xs.jpg",
    "tags": "3d,action,army,battle-royale,first-person-shooter,free,io-games,shooting",
    "description": "You are a particular elite team member and are called into battle.  Your weapons are ready, and your equipment is prepared.  All your team needs is you.  Guerrillas io is a multiplayer battling game that you can play online.",
    "category": "Shooting",
    "views": 7807870,
    "date": "2024-03-05T10:22:42",
    "developer": "Turbo Games"
  },
  {
    "id": "checkout-frenzy",
    "title": "Checkout Frenzy",
    "embed": "https://cloud.onlinegames.io/games/2025/unity/checkout-frenzy/index-og.html",
    "url": "https://cloud.onlinegames.io/games/2025/unity/checkout-frenzy/index-og.html",
    "image": "https://www.onlinegames.io/media/posts/974/responsive/checkout-frenzy-cashier-game-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/974/responsive/checkout-frenzy-cashier-game-xs.jpg",
    "tags": "1-player,3d,free,organizing,simulator,tycoon,unity",
    "description": "Have you ever stood in line at a store and wondered, “What exactly are the cashiers doing on that screen? ” All those bippity boppity beeps and flashing buttons...  What do they even mean?  Okay, we'll solve that mystery.",
    "category": "Simulator",
    "views": 6450753,
    "date": "2021-08-11T10:22:42",
    "developer": "Pixel Dreams"
  },
  {
    "id": "cs-online",
    "title": "CS Online",
    "embed": "https://www.onlinegames.io/games/2023/unity2/cs-online/index.html",
    "url": "https://www.onlinegames.io/games/2023/unity2/cs-online/index.html",
    "image": "https://www.onlinegames.io/media/posts/434/responsive/CS-Online-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/434/responsive/CS-Online-xs.jpg",
    "tags": "3d,action,battle,battle-royale,first-person-shooter,free,gun,multiplayer,shooting,unity,war,weapon",
    "description": "Everyone knows the famous Counter Strike game, 2000's online battle arena with online players.  CS Online, inspired by Counter-Strike, is a multiplayer shooting game where terrorists and counter-terrorists combat and kill each other with multiple weapon options.  It is the online and free version of the original game, and you can access the CS Online on your web browser without downloading or purchasing anything.  All you need to do is join an available room and start to play!",
    "category": "Shooting",
    "views": 5018715,
    "date": "2025-10-26T10:22:42",
    "developer": "Digital Forge"
  },
  {
    "id": "escape-car",
    "title": "Escape Car",
    "embed": "https://cloud.onlinegames.io/games/2025/unity2/escape-car/index-og.html",
    "url": "https://cloud.onlinegames.io/games/2025/unity2/escape-car/index-og.html",
    "image": "https://www.onlinegames.io/media/posts/1000/responsive/Escape-Car-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/1000/responsive/Escape-Car-xs.jpg",
    "tags": "1-player,3d,car,crazy,drift,driving,free,gta,html5,mobile,police,skill,speed,traffic",
    "description": "Do you remember the very first Grand Theft Auto?  That old-school, top-down chaos.  Think of that and give it a fresh coat of chunky 3D graphics.  Next, drop that straight in your browser.",
    "category": "Drift",
    "views": 6167228,
    "date": "2024-05-28T10:22:42",
    "developer": "Studio X"
  },
  {
    "id": "99-nights-in-the-forest",
    "title": "99 Nights in the Forest",
    "embed": "https://cloud.onlinegames.io/games/2026/unity/99-nights-in-the-forest-survival/game.html",
    "url": "https://cloud.onlinegames.io/games/2026/unity/99-nights-in-the-forest-survival/game.html",
    "image": "https://www.onlinegames.io/media/posts/1190/responsive/99-nights-in-the-forest-xs.webp",
    "thumbnail": "https://www.onlinegames.io/media/posts/1190/responsive/99-nights-in-the-forest-xs.webp",
    "tags": "1-player,3d,adventure,crafting,defense,free,mouse,roblox,survival,unity,weapon",
    "description": "99 Nights in the Forest is an online survival game where you find yourself in a deserted forest.  To be able to survive for 99 nights, you need to guard yourself from all possible dangers, including werewolves.  Craft tools by collecting wood and other materials that you can find in the forest.  Light a campfire to stay warm at night!",
    "category": "Strategy",
    "views": 1266941,
    "date": "2021-06-04T10:22:42",
    "developer": "Digital Dreams"
  },
  {
    "id": "basket-hoop",
    "title": "Basket Hoop",
    "embed": "https://cloud.onlinegames.io/games/2024/construct/311/basket-hoop/index-og.html",
    "url": "https://cloud.onlinegames.io/games/2024/construct/311/basket-hoop/index-og.html",
    "image": "https://www.onlinegames.io/media/posts/843/responsive/Basket-Hoop-xs.jpg",
    "thumbnail": "https://www.onlinegames.io/media/posts/843/responsive/Basket-Hoop-xs.jpg",
    "tags": "1-player,2d,ball,basketball,endless,free,html5,mobile,mouse,physics,skill,sports",
    "description": "In Basket Hoop, gravity is your only challenge, and tapping is your sole weapon.  Your goal is simple make the ball jump and send it inside the hoop.  The charm of the one button games peaks in Basket Hoop online.  Make as many baskets as you can in a limited amount of time.",
    "category": "Sports",
    "views": 4955124,
    "date": "2021-08-13T10:22:42",
    "developer": "Digital Dreams"
  },
  {
    "id": "fall-brainrots",
    "title": "Fall Brainrots",
    "embed": "https://cloud.onlinegames.io/games/2026/unity/fall-brainrots/game.html",
    "url": "https://cloud.onlinegames.io/games/2026/unity/fall-brainrots/game.html",
    "image": "https://www.onlinegames.io/media/posts/1194/responsive/fall-brainrots-xs.webp",
    "thumbnail": "https://www.onlinegames.io/media/posts/1194/responsive/fall-brainrots-xs.webp",
    "tags": "3d,avoid,brainrot,crazy,free,funny,mouse,multiplayer,parkour,physics,racing,skill,unity",
    "description": "Fall Brainrots is a multiplayer parkour game in which you try to survive in various tracks with your Italian brainrot character.  Dodge obstacles and reach the finish line first in each course.  You must avoid falling; otherwise, you will be eliminated!  With its silly Brainrot characters, it’s a pretty enjoyable mix of platformer games and Italian brainrot games.",
    "category": "Racing",
    "views": 1794522,
    "date": "2023-04-20T10:22:42",
    "developer": "Retro Works"
  }
];
